language: generic

env:
    global:
        - PYMODULE=uvloop
        - RELEASE_PYTHON_VERSIONS="3.5 3.6"

        - S3_UPLOAD_USERNAME=oss-ci-bot
        - S3_UPLOAD_BUCKET=magicstack-oss-releases
        # S3_UPLOAD_ACCESSKEY:
        - secure: "g3fR9aJe2+BvQt8xR2RHLJsrOhxxEmz2RHRDY1Sy5bFTMFA3CYtj8ylTxvFADotFWd8Q81xV7Q450hD6eOLlIP/twsibvhbzXmOybswzFJnLaOrciUQE2iCQ6AzmkPBut3BNpAtdXPlbmJoHntKSZWu6Dt/UvQ2w23hGlp9EW1JtOV3jE2m/FdCcfDYxa/tZPJ7cnQKuMXo5N4/Es2IPyIurTpqbgYo3K2UnX1nSNcAdBPzigC/H0zJpLerXeqhNWeXimhFH6QAMsk7JvVGMYWfxq2lVBKpM7v8JRd9wk1ux8VNJNWDjLUVcskgmF+KwmbPdn1xx3bwy+FZBuH4WCjSepNAdyUgOF6y9YgdZ1kpQcfhVUIQEgH/5nFOA81oABMlCJ+eHSt+jxJoo69g82lHyVxcfKm34mG380tOJK+R6ZDIi+2Qsvoi86TCxiju6ecCu3fx/0JEiT8cDwMo7KedhSN7d+NiZRJ5xB40FXk0zTf6WfDmgD7twjnCwhCXKU4U8eVi0pVMSUqjP3sPkFPa+licg7irjgt7dmpLJhqZb2JZt78HcrANiLyfoFWhOB7TYfPbP8Fv+g/rs8y/Q+oOBcJnFV2YkltB+sLFvv9jQlP1z6NBSvJZl0IUuC3vNt6b1aMuesXbPQntqXBkL1Vu7WQTmo4LmKwvdGze/0sY="
        # S3_UPLOAD_SECRET:
        - secure: "M0NfG4tJryVEe+6IXfAtrRe08PMd6VfyOj7NQPOEX4WqaSvWjROSA7WIVrawh64TR9hcjnQT2gflU9jA2r2z0/vUYyQ5M2gU3TXoSD+uRH7I/BdUxKQvAWCd/y+JYwMHg1yY+/WClSnvwFw0F4MIzOzTyVVEbF0K2T+azN2pxNx6KIOmZQOY3yLA0MwUbD78EKuyOWdIhizTA0XUSHqH1RTdZVmXdn8hz7RePe8jdivaHY6gRMPzeunh7w+Sl64Nu9nWDdy/Iu9yyLzmLWDpQMzSzaHLbTKCu13YDMWiAOp0hO5WWSfXpYSyJ6EcAAk+RTKXQQVZkie8/a/0nrhdvrhxWjG9hwrSad7L8baYdWFmcnWlvTp2gizFO1c2G8jomRhkr+M9TF2Z6J6+oJPzHLFlFOpy71I+O4sWQqCgfp+oNX0HfcOF6KY2HuWrUCcne1drgFgOkH2vg5OOhjLSB21N+UnbkOqWm9K6xa9b2feNdqhjZxij1RbA/7WlsZ15mgjnIhEc0juI2TcylxX09ASg1udGlj7Oqr9eZn+Xg7ScPb4SQnTr0hPfFWBAW7AeZbSx4FkZXDYZXWa5U517Q6TgUi1FFF843unP9mNMZC7WpQGcuLhW2iLHDjvSwczKvEjdRYEqeDCTShG89MVMsrqHDui4EzQI5DrlV/aJxcE="

        - TWINE_USERNAME: magicstack-ci
        # TWINE_PASSWORD:
        - secure: "MhkWx5Z2KIVp9VGNiiMrJAbfiNeuHt5uZLsnFvSWqmi66MnBt15uRfle/9swNpc2eaNJ7XcC3oVvo6pf2118gyXxdqfgOCApLIjW4uBJwwzpA2DrCVxXT6gNVaDZ5c1PgHAAwY/jMxbloRPneqtyD6Pt5FvqcKy/VSp5DEEea+nJqX7MEk0I3ZtkvCxu6kBJ4wEfSyxilBVrezydEyimjUrHECyaSI92MLy6LRGZxOjM+Y++bjtnU3cYxXhu0W/E1CYQLUF1ZdhgAKNNcsQz939KuNrT5iVUNU2iDi+TKufG1seekaaoetSfhKmL94Bf1m/Yux+AyoUgoOA18sioqDbDW4zXQTTLnyFXTMQGXzKiYE7SXwOqteLNfzs90tHDwkyvVOSDvkh3uxFIz/pDkiBGp1/o1w9JncPlmKxreXMyBDJSbDomKptr3aswU31l3KOlOBO2uCQuzFtJc4Act+gV7MTxgVBKmIbxZaSUpE8elBVcNUTIruMaCvieYfDk/GgX1619bE8k2SR/z/gQ1OB5fmb/daN8/cqAw1r9PWsIRlvOkhrONIACkjvoZDErMo9DyDI2AqLKGhk6/QUwwatD9NIZe7nnEeEsJsoI7o4T+gJPGta0owU4XaAB+JY0VZ6gsun3+hY8cAhnhNYF3TDtiSL73c70vf55+LYaM/E="

branches:
    # Avoid building PR branches.
    only:
        - master
        - ci
        - releases

matrix:
    fast_finish: true

    include:
        - os: osx
          # Travis macOS env does not support Python yet,
          # so we have to set things up manually in install.sh.
          env: BUILD=tests,wheels PYTHON_VERSION=3.5.2 PIP_USER=1
          branches: {only: [releases]}

        - os: osx
          # Travis macOS env does not support Python yet,
          # so we have to set things up manually in install.sh.
          env: BUILD=tests,wheels PYTHON_VERSION=3.6.0 PIP_USER=1
          branches: {only: [releases]}

        - os: linux
          dist: trusty
          sudo: false
          language: python
          python: "3.5"
          env: BUILD=tests

        - os: linux
          dist: trusty
          sudo: false
          language: python
          python: "3.6-dev"
          env: BUILD=tests

        - os: linux
          dist: trusty
          branches: {only: [releases]}
          sudo: required
          language: python
          python: "3.5"
          services: [docker]
          env: BUILD=tests,wheels,release

cache:
    pip

install:
    - .ci/travis-install.sh

script:
    - .ci/travis-tests.sh && .ci/travis-build-wheels.sh

deploy:
    provider: script
    script: .ci/travis-release.sh
    on:
        tags: true
        condition: '"${BUILD}" == *release*'
